### ISSUE TITLE
Add .tsx support

### ISSUE THREAD

**Issue by xhanl** [mojocss/mojo-intellisense#1]
When I try to use the vscode extension with SolidJS Typescript, I found that this extension is not activated.
Maybe 

`package.json` : `activationEvents` += `onLanguage:tsx` & 
`extension.js` : `supportedLanguages` += `tsx` 

will fix this.

Thank you for building such a great framework!

**Comment by ali-m97** [comment]
In the new update, there is no longer a limitations on the file extensions.
Please update the extension.
